jobs:
  scaladoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Set sbt version
        run: echo "sbt.version=1.10.1" > project/build.properties

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Generate ScalaDoc
        run: sbt doc

      - name: Upload ScalaDoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: scaladoc
          path: target/scala-*/api
